# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        hwi:
            id: hwi_oauth.user.provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
                            pattern: ^/
                            anonymous: ~
                            oauth:
                                resource_owners:
                                    spotify: /login/check-spotify
                                login_path:        /login
                                use_forward:       false
                                failure_path:      /login
                                oauth_user_provider:
                                    service: hwi_oauth.user.provider

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login/check-spotify, roles: IS_AUTHENTICATED_ANONYMOUSLY }